### ISSUE TITLE
정적 파일 요청시 발생하는 에러로 알게된 문제

### ISSUE THREAD

**Issue by nashs789** [c4fiber/DoWith_backend#52]
- 서버에 없는 파일을 여러번 요청하게 되면 발생하는 문제

에러를 발생 시키는데 현재 Interceptor에서 DB로 에러 로그를 쌓고 있는데 한 번에 여러번 요청을 처리해야 하다 보니까 동기적으로 처리하면서 DB 풀 한계점에 도달해서 리소스 대기하느라고 버벅이는 것 같음

**Comment by nashs789** [comment]
별개의 문제로 queryRunner를 사용한 후 리소스 해제(release)를 안하는 걸로도 메모리 누수 문제가 있었음

**Comment by c4fiber** [comment]
# 존재하지 않는 static resource를 요청할 때 생기는 서버 문제

문제가 발생한 코드

**do-with-exception.filter.ts**

```jsx
import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  HttpException,
  Logger,
  HttpStatus,
} from '@nestjs/common';
import { Request, Response } from 'express';
import { DoWithException } from 'src/do-with-exception/do-with-exception';
import { doWithError } from 'src/error-log/entities/error.entity';
import { DataSource } from 'typeorm';

@Catch()
export class DoWithExceptionFilter implements ExceptionFilter {
  constructor(private readonly dataSource: DataSource) {}
  private readonly logger = new Logger();

  async catch(exception: DoWithException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const res = ctx.getResponse<Response>();
    const req = ctx.getRequest<Request>();
    const err = new doWithError();
    let comRes = {
      timestamp: new Date().toISOString(),
      name: exception.name,
      message: exception.message,
      path: req.url,
    };

    this.logger.error(exception.stack);

    // 요구 사항에 따라서 밑에 코드 변경 예정
    if (exception.name === 'DoWithException') {
      err.err_code = exception.getErrCode();
      err.http_code = exception.getStatus();
      comRes['errCode'] = err.err_code;
    }

    if (exception instanceof HttpException) {
      err.http_code = exception.getStatus();
    } else {
      err.http_code = HttpStatus.INTERNAL_SERVER_ERROR;
    }

    res.status(err.http_code);

    const queryRunner = this.dataSource.createQueryRunner();
    try {
      err.method = req.method;
      err.url = req.url;
      err.agent = req.headers['user-agent'];
      err.ip = req.ip;
      err.parameters = req.body;
      err.err_name = exception.name;
      err.err_stack = exception.stack;

      queryRunner.manager.save(doWithError, err);
    } catch (err) {
      // 조치 없음
      this.logger.error('DB Insert Exception');
    } finally {
      queryRunner.isReleased || queryRunner.release();
    }

    res.json(comRes);
  }
}
```

try 문으로 시작하는 코드는 error 메세지를 DB에 저장하는 역할을 합니다.

frontend에서 방명록을 불러오는 과정에서 /image/{{user_id}}.jpg 를 요청합니다.

static resource를 서버에 요청할때 (ex: /image/1.jpg) 사진이 없을 경우 NOTFOUND exception이 발생합니다.

이 exception은 프로젝트에서 custom한 do-with-exception으로 넘어가게되는데

이 과정에서 DB에 기록을 하는 코드입니다.

첫번째 문제는 이전에 queryRunner.relase()를 호출하지 않아서 리소스가 해제되지 않고 유지되는 문제가 발생

→ release 메소드를 호출하며 해결

두번째 문제는 release를 isReleased를 체크하지 않았을 경우

queryRunner already Released라는 에러를 발생시킵니다.

→ release 여부를 확인해서 해제하도록 변경

chatGPT 답변: 

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/ff71667d-210a-495b-80ce-265af0a40016/a6b85c95-00dc-4d5b-8324-88f042cee8ef/Untitled.png)

이 두가지 문제를 해결하고도 방명록을 열었을 때 일시적으로 서버가 멈추는 상황이 발생했습니다.

현재 정확한 원인은 인식되지 않았으며 방명록이 아닌 thunder client 혹은 postman으로 다발적으로 요청한 경우는 정상적으로 처리됩니다.

하지만 방명록 처럼 한번에 여러 image를 요청하는 경우에는 여전히 문제가 발생하고 있습니다.

11-30 기준으로 문제가 발생하면 서버가 일시적으로 멈추었다가 작동합니다.

현재 문제지점 코드는 다음과 같습니다

**Comment by nashs789** [comment]
release와 같은 문제로 현재는 발생되지 않은지 오래된 이슈이기 때문에 close 합니다.
